from . import inherited_equipment_category
from . import equipment_checklist_question
from . import inherited_equipment
from . import inherited_maintenance_request
from . import equipment_spare_part
from . import equipment_daily_report
from . import equipment_daily_report_line
from . import res_users
from . import equipment_dashboard